### ISSUE TITLE
App crashes when trying to edit an already existing post

### ISSUE THREAD

**Issue by wyattf1995** [EdiWang/Moonglade#200]
**Describe the bug**

The app crashes when you try to edit an already existing post. 

**To Reproduce**
1. Link to database
2. Make a post
3. Try to edit that post

**Expected behavior**
To be able to edit the post

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
 Logs:

2019-06-05 16:16:40.5590|LAPTOP-3A929AQ6|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.,System.InvalidOperationException: Error generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.DetachedLazyLoadingWarning: An attempt was made to lazy-load navigation property 'PostTag' on detached entity of type 'PostEntityProxy'. Lazy-loading is not supported for detached entities or entities that are loaded with 'AsNoTracking()'.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.DetachedLazyLoadingWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
   at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam1 arg1, TParam2 arg2, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.CoreLoggerExtensions.DetachedLazyLoadingWarning(IDiagnosticsLogger`1 diagnostics, DbContext context, Object entityType, String navigationName)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.ShouldLoad(Object entity, String navigationName, NavigationEntry& navigationEntry)
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.PostEntityProxy.get_PostTag()
   at Moonglade.Web.Controllers.PostController.Edit(Guid id) in C:\Users\Wyatt\Desktop\Moonglade\src\Moonglade.Web\Controllers\PostController.Manage.cs:line 142
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Moonglade.Web.Middleware.RobotsTxt.RobotsTxtMiddleware.Invoke(HttpContext context) in C:\Users\Wyatt\Desktop\Moonglade\src\Moonglade.Web.Middleware\RobotsTxt\RobotsTxtMiddleware.cs:line 39
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context),GET https://localhost/post/manage/edit,Edit,::1
2019-06-05 16:16:40.6352|LAPTOP-3A929AQ6|INFO|Microsoft.AspNetCore.Routing.EndpointMiddleware|Executing endpoint 'Moonglade.Web.Controllers.ErrorController.Error (Moonglade.Web)',GET https://localhost/error,Error,::1
2019-06-05 16:16:40.6352|LAPTOP-3A929AQ6|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Route matched with {action = "Error", controller = "Error"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Error(System.Nullable`1[System.Int32]) on controller Moonglade.Web.Controllers.ErrorController (Moonglade.Web).,GET https://localhost/error,Error,::1
2019-06-05 16:16:40.6352|LAPTOP-3A929AQ6|INFO|Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker|Executing action method Moonglade.Web.Controllers.ErrorController.Error (Moonglade.Web) - Validation state: Valid,GET https://localhost/error,Error,::1
2019-06-05 16:16:40.6352|LAPTOP-3A929AQ6|ERROR|Moonglade.Web.Controllers.ErrorController|Shit happens: /post/manage/edit, client IP: ::1,GET https://localhost/error,Error,::1

**Comment by EdiWang** [comment]
@wyattf1995 

Thank you for reporting the bug. As my initial investigation, creating a post **without any tags will result in this exception** when trying to edit the post.

This is caused by a design flaw in PostService.cs. ```public Response<PostEntity> GetPost(Guid id)```, service class should not return any type of EF entity to the upper layer. 

I'm currently in the middle of refactoring this kind of design flaws. As for now, you will have to create a post with **at least one tag** to workaround this issue.

I'll fix this bug ASAP.

**Comment by wyattf1995** [comment]
Ah got it, thank you for the quick reply. I was messing around with it for a few hours this morning and kept hitting dead ends and it definitely seems par for the course that it'd be something as simple as that that I was overlooking. The tag being a necessity is a very manageable inconvenience.

Also, since I have your attention I have been having issues uploading images and would love to hear the method you use when you add images to a blog post. When I try to upload images to a post I get the "no-hotlinking" image. I registered an Azure CDN and set the appsettings config value to True and am still receiving the "no hotlinking" image. I am curious what you do to assure not getting the error image.

Really appreciate all the work you've put into this code, I really like the whole system.

**Comment by EdiWang** [comment]
@wyattf1995 

I believe you are uploading the image correctly. The "No Hot Link" is caused by a url rewrite rule under \src\Moonglade.Web\urlrewrite.xml, you can find

```
<rule name="Prevent Image Hotlinking">
  <match url=".*\.(gif|jpg|png)$"/>
  <conditions>
    <add input="{HTTP_REFERER}" pattern="^$" negate="true"/>
    <add input="{HTTP_REFERER}" pattern="^https?:\/\/.*edi.wang:?\d{0,5}?\/.*$" negate="true"/>
    <add input="{HTTP_REFERER}" pattern="^https?:\/\/localhost:?\d{0,5}?\/.*$" negate="true"/>
    <add input="{HTTP_REFERER}" pattern="^https?:\/\/.*azurewebsites.net:?\d{0,5}?\/.*$" negate="true"/>
  </conditions>
  <action type="Rewrite" url="/images/no_hotlinking.png"/>
</rule>
```
This prevents unauthorized link to your blog site. Just change the domain in the pattern to match your website domain and local domain, you should get the image working.

**Comment by EdiWang** [comment]
@wyattf1995 and also there are few more places I haven't completely removed the "edi.wang" related stuff, like the page footer. In the long term, all edi.wang specific code will be removed and the blog system could be then used in general. Currently, to make a blog site for your own use, you will have to change those places. I'm willing to help you to get your website running.

**Comment by EdiWang** [comment]
@wyattf1995 the issue is fixed, please use the latest code in master branch. 

BTW, for images, you don't have to use Azure CDN if you haven't encountered enough user load. Azure CDN costs you extra money. Just turn off the GetImageByCDNRedirect in appsettings.json. The blog will then fetch the image via a backend call to Azure Blob Storage and cache the image in memory.

```
"GetImageByCDNRedirect": false
```

**Comment by wyattf1995** [comment]
Thanks for all the help and addressing the issue so quickly. Good to know about the CDN though and I found this [link](https://edi.wang/post/2018/9/18/prevent-image-hotlink-aspnet-core) on your blog very helpful in explaining the theoretical basis for the URL rewrite, so thanks for putting that up. Getting a custom site like this up has been quite a daunting task for a relative beginner like myself so I appreciate all the help and will contact you if I run in to any further issues!
