### ISSUE TITLE
captha image issue

### ISSUE THREAD

**Issue by TonyWoo** [EdiWang/Moonglade#595]
After deploying the blog system to Azure Linux web app, I noticed the captcha image is not displaying when login to the admin. After checked the network request, it shows the Aria could not be found, see below. It seems the Azure Linux app doesn't install the Arial font? BTW, thanks for providing a great blog system.

SixLabors.Fonts.Exceptions.FontFamilyNotFoundException: Arial could not be found
   at SixLabors.Fonts.FontCollection.FindInternal(String fontFamily, CultureInfo culture)
   at SixLabors.Fonts.FontCollection.Find(String fontFamily)
   at SixLabors.Fonts.SystemFontCollection.Find(String fontFamily)
   at Edi.Captcha.CaptchaImageGenerator.GetImage(Int32 width, Int32 height, String captchaCode, FontStyle fontStyle)
   at Edi.Captcha.SessionBasedCaptcha.GenerateCaptchaImageBytes(ISession httpSession, Int32 width, Int32 height)
   at Edi.Captcha.CaptchaImageMiddleware.Invoke(HttpContext context, ISessionBasedCaptcha captcha)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Moonglade.Web.Middleware.DefaultImageMiddleware.Invoke(HttpContext context, IBlogConfig blogConfig) in D:\Work\Moonglade\src\Moonglade.Web\Middleware\DefaultImageMiddleware.cs:line 19
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by EdiWang** [comment]
This issue has just been fixed today. If your Azure deployment is using Linux App Service plan with Docker, please use the latest docker image `docker pull ediwang/moonglade`.

**Comment by TonyWoo** [comment]
I didn't use the docker. How to copy the font file to Linux server folder(usr/share/fonts/)? I'm using Linux app service plan?

Maybe the font need to be included under the app folder?

**Comment by EdiWang** [comment]
Unfortunately you can't copy the font to a managed App Service Plan. To use Moonglade on Azure, you have to use Windows App Service Plan with code deployment or Linux App Service Plan with Docker.

But still, I'll try to fix the font issue which was introduced in v11.9  and make Moonglade deployment works on Linux without Docker like before.

**Comment by TonyWoo** [comment]
Thank you. I found the same result, I'm trying to deploy it to a windows app service plan.

**Comment by EdiWang** [comment]
Will be fixed in v12.0
